name: Import FoD results to GitHub

on: [workflow_dispatch]

jobs:
  FoD-Import:
    runs-on: windows-latest

    steps:
      - name: Check Out Source Code # We don't need source code, but upload-sarif action wants a git repo
        uses: actions/checkout@v2
      - name: Import results to GitHub Security Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ./gh-fod-sast.sarif
